# Generated by Django 3.0.8 on 2021-07-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicapp.Companies')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicapp.Contractor')),
            ],
        ),
    ]
