# Generated by Django 3.0.8 on 2021-07-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.TimeField(),
        ),
    ]
