# Generated by Django 3.0.8 on 2021-07-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0003_auto_20210709_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='contractor',
            field=models.CharField(max_length=50),
        ),
    ]
